[palette]
black = '#2E3440'
gray = '#4C566A'
light = '#D8DEE9'
white = '#ECEFF4'
teal = '#8FBCBB'
lake = '#88C0D0'
frost = '#81A1C1'
blue = '#5E81AC'
red = '#BF616A'
orange = '#D08770'
yellow = '#EBCB8B'
green = '#A3BE8C'
purple = '#B48EAD'

[symbols]
home = " "
read_only = ""
truncate = "…"
python = ""
duration = ""
time = ""

[symbols.os]
windows = "󰍲"
ubuntu = "󰕈"
suse = ""
raspbian = "󰐿"
mint = "󰣭"
macos = "󰀵"
manjaro = ""
linux = "󰌽"
gentoo = "󰣨"
fedora = "󰣛"
alpine = ""
amazon = ""
android = ""
arch = "󰣇"
artix = "󰣇"
centos = ""
debian = "󰣚"
redhat = "󱄛"
redhatenterprise = "󱄛"

[symbols.git]
symbol = ""
branch = "󰘬"
ahead = '⇡'
behind = '⇣'
conflicted = "="
untracked = "?"
stashed = "\\$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
ignored = ''

[username]
disabled = false
show_always = true
format = '[$user]($style) @ '
style_user = 'bold yellow'
style_root = 'bold red'

[hostname]
ssh_only = true
style = "bg:dark4 fg:accent3 bold"
format = "[@($ssh_symbol )$hostname ]($style)"

[directory]
format = "[$path ]($style)[$read_only]($read_only_style)"
style = "bg:theme4 fg:light3"
home_symbol = " "
truncation_symbol = "…"
truncate_to_repo = true
read_only = ""
read_only_style = "bg:theme4 fg:accent1"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Code" = "󰲋 "

[git_branch]
symbol = "󰘬"
style = "bg:accent3 fg:dark2 bold"
format = "[ $symbol$branch(:$remote_branch) ]($style)"

[git_status]
format = "([$all_status$ahead_behind ]($style))"
style = "bg:accent3 fg:accent1 bold"
ahead = '⇡'
behind = '⇣'
conflicted = "="
untracked = "?"
stashed = "\\$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[python]
symbol = ""
style = "bg:theme4 fg:accent3"
format = '([](fg:theme4)[$symbol $virtualenv]($style)[](fg:theme4)) '

[cmd_duration]
format = "[ $duration  ]($style)"
style = "bg:accent5 fg:dark2 bold"
min_time = 2000


[time]
disabled = false
# time_format = "%R"
style = "bg:light1 fg:dark1"
format = '[ $time  ]($style)'
