"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[╭─](default_dimmed)\
(os)
[╰─](default_dimmed)\
"""

[palette]
dark1 = '#2E3440'
dark2 = '#3B4252'
dark3 = '#434C5E'
dark4 = '#4C566A'
light1 = '#D8DEE9'
light2 = '#E5E9F0'
light3 = '#ECEFF4'
theme1 = '#8FBCBB'
theme2 = '#88C0D0'
theme3 = '#81A1C1'
theme4 = '#5E81AC'
accent1 = '#BF616A'
accent2 = '#D08770'
accent3 = '#EBCB8B'
accent4 = '#A3BE8C'
accent5 = '#B48EAD'

[os.symbols]
windows = "󰍲 "
ubuntu = "󰕈 "
suse = " "
raspbian = "󰐿 "
mint = "󰣭 "
macos = "󰀵 "
manjaro = " "
linux = "󰌽 "
gentoo = "󰣨 "
fedora = "󰣛 "
alpine = " "
amazon = " "
android = " "
arch = "󰣇 "
artix = "󰣇 "
centos = " "
debian = "󰣚 "
redhat = "󱄛 "
redhatenterprise = "󱄛 "

[username]
disabled = false
show_always = true
format = '[$user]($style) @ '
style_user = 'bold yellow'
style_root = 'bold red'

[hostname]
ssh_only = true
style = "bg:dark4 fg:accent3 bold"
format = "[@($ssh_symbol )$hostname ]($style)"

[directory]
format = "[$path ]($style)[$read_only]($read_only_style)"
style = "bg:theme4 fg:light3"
home_symbol = ""
truncation_symbol = "…"
truncate_to_repo = true
read_only = ""
read_only_style = "bg:theme4 fg:accent1"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Code" = "󰲋 "

[git_branch]
symbol = "󰘬"
style = "bg:accent3 fg:dark2 bold"
format = "[ $symbol$branch(:$remote_branch) ]($style)"

[git_status]
format = "([$all_status$ahead_behind ]($style))"
style = "bg:accent3 fg:accent1 bold"
ahead = '⇡'
behind = '⇣'
conflicted = "="
untracked = "?"
stashed = "\\$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[python]
symbol = ""
style = "bg:theme4 fg:accent3"
format = '([](fg:theme4)[$symbol $virtualenv]($style)[](fg:theme4)) '

[cmd_duration]
format = "[ $duration  ]($style)"
style = "bg:accent5 fg:dark2 bold"

[time]
disabled = false
# time_format = "%R"
style = "bg:light1 fg:dark1"
format = '[ $time  ]($style)'
