"$schema" = 'https://starship.rs/config-schema.json'

# add_newline = true
scan_timeout = 10

palette = 'nord'

# format = ""
# right_format = ""

continuation_prompt = "[∙∙∙](bright-black)     "

format = """\
[╭─](fg:light1)$os[](fg:light1 bg:dark1)\
([ ](fg:dark1 bg:dark4)$username$hostname[](fg:dark4 bg:dark1))\
[ ](fg:dark1 bg:theme4)$directory[](fg:theme4 bg:accent3)\
$git_branch$git_status[](fg:accent3 bg:dark1) \
$fill \
$python\
[](fg:accent5)$cmd_duration\
[](bg:accent5 fg:light1)$time\
\
"""
# [╰─](light1)$character\

# right_format = """\
# """

[palettes.nord]
dark1 = '#2E3440'
dark2 = '#3B4252'
dark3 = '#434C5E'
dark4 = '#4C566A'
light1 = '#D8DEE9'
light2 = '#E5E9F0'
light3 = '#ECEFF4'
theme1 = '#8FBCBB'
theme2 = '#88C0D0'
theme3 = '#81A1C1'
theme4 = '#5E81AC'
accent1 = '#BF616A'
accent2 = '#D08770'
accent3 = '#EBCB8B'
accent4 = '#A3BE8C'
accent5 = '#B48EAD'


[fill]
symbol = "∙"

[os]
disabled = false
style = "bg:light1 fg:theme4"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[username]
show_always = false
format = '[$user]($style)'
style_user = 'bg:dark4 fg:accent4'
style_root = 'bg:dark4 bold red'

[hostname]
ssh_only = true
style = "bg:dark4 fg:accent3 bold"
format = "[@($ssh_symbol )$hostname ]($style)"

[directory]
format = "[$path ]($style)[$read_only]($read_only_style)"
style = "bg:theme4 fg:light3"
home_symbol = " "
truncation_symbol = "…/"
read_only = " "
read_only_style = "bg:theme4 fg:accent1"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Code" = "󰲋 "

[git_branch]
symbol = " 󰘬 "
style = "bg:accent3 fg:dark2 bold"
format = "[ $symbol$branch(:$remote_branch) ]($style)"

[git_status]
format = "([$all_status$ahead_behind ]($style))"
style = "bg:accent3 fg:accent1 bold"
conflicted = "=$count"
untracked = "?$count"
stashed = "\\$$count"
modified = "!$count"
staged = "+$count"
renamed = "»$count"
deleted = "✘$count"

[python]
symbol = ""
style = "bg:theme4 fg:accent3"
format = '([](fg:theme4)[$symbol $virtualenv]($style)[](fg:theme4)) '

[cmd_duration]
format = "[ $duration  ]($style)"
style = "bg:accent5 fg:dark2 bold"

[time]
disabled = false
# time_format = "%R"
style = "bg:light1 fg:dark1"
format = '[ $time  ]($style)'

[character]
disabled = true
success_symbol = '[ ](bold fg:green)'
error_symbol = '[ ](bold fg:red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
